spring:
  application:
    name: auth-service
  config:
    import: classpath:env.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flexyMart_auth
    username: DB_USER
    password: DB_PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8070
